version: "3.9"

services:
  osint-app:
    container_name: osint-app
    build: .
    image: rybalka-osint-app
    depends_on:
      - postgres
    volumes:
      - ./volumes/data:/app/data
      - ./volumes/logs:/app/logs
      - ./volumes/output:/app/output
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://osint-postgres:5432/osintdb
      DB_USER: osintuser
      DB_PASSWORD: osintpass
    networks:
      - osint-net
    command: ["--scan", "-o", "stdout", "microsoft.com"]

  postgres:
    image: postgres:15
    container_name: osint-postgres
    restart: always
    ports:
      - "2432:5432"
    environment:
      POSTGRES_DB: osintdb
      POSTGRES_USER: osintuser
      POSTGRES_PASSWORD: osintpass
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - osint-net

  amass:
    image: caffix/amass
    container_name: amass
    restart: always
    networks:
      - osint-net
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./volumes/config:/.config/amass:rw
      - ./volumes/data/amass:/data:rw

  theharvester:
    image: simonthomas/theharvester
    container_name: theharvester
    restart: always
    tty: true
    stdin_open: true
    networks:
      - osint-net

networks:
  osint-net: